### ISSUE TITLE
Support "Geyser" editing (WorldSpawner / Prefab)

### ISSUE THREAD

**Issue by RoboPhred** [RoboPhred/oni-save-parser#1]
Core request is to tweak the element and temperature on new saves (presumably, ahead of discovery).

These exist in 2 forms through the game.  Before they are discovered, they are a WorldSpawner.  After, they are a "Geyser" Prefab.

## WorldSpawner
These are simple.  I found one before, and it stores the element ID, temperature, and a few other values.
I need to look this up again; I do not have access to ONI at the moment.

## Prefab
"Geyser"
- Inspect ElementEmitter behavior - where does it get its element from?  Probably PrimaryElement.
- Inspect "Geyser" behavior - Does this do anything interesting for us?  It has no template data or extra data.
- StateMachineController - Might be initialized data stored in here for things we want to edit (rates, element, temperature...).  It will be useful to parse these, as most game objects make use of it.

Geyser prefab behavior chunk example:
*first entry in [THE LOST CITY](https://forums.kleientertainment.com/topic/86290-the-lost-city-challenge-map/) challenge geyser prefabs.*
```
[
              {
                "name": "KPrefabID",
                "hasParseData": true,
                "parsedData": {
                  "InstanceID": 2002
                },
                "extraData": null
              },
              {
                "name": "SavedObject",
                "hasParseData": true,
                "parsedData": {
                  "inStorage": false
                },
                "extraData": null
              },
              {
                "name": "StateMachineController",
                "hasParseData": true,
                "parsedData": {},
                "extraData": {}
              },
              {
                "name": "PrimaryElement",
                "hasParseData": true,
                "parsedData": {
                  "ElementID": -355957251,
                  "_Temperature": 374.4565124511719,
                  "diseaseID": {
                    "hash": 0
                  },
                  "diseaseCount": 0,
                  "Units": 1
                },
                "extraData": null
              },
              {
                "name": "Klei.AI.Modifiers",
                "hasParseData": true,
                "parsedData": {},
                "extraData": {}
              },
              {
                "name": "Geyser",
                "hasParseData": true,
                "parsedData": {},
                "extraData": null
              },
              {
                "name": "ElementEmitter",
                "hasParseData": true,
                "parsedData": {},
                "extraData": null
              }
            ]
```

**Comment by TheLoneWolfling** [comment]
Ugh, State machines completely ignore the template type system for their internal data. This is going to be annoying.

**Comment by RoboPhred** [comment]
I added editing of the Geyser behavior, which only functions when the geyser has been revealed.  The editables are pretty restricted; only the random factor can be changed, and only existing geyser types can be selected.  No custom elements or never-idle geysers.

Templates and helper functions have been added.
