### ISSUE TITLE
What's contained in the simdata?

### ISSUE THREAD

**Issue by StefanOltmann** [RoboPhred/oni-save-parser#22]
One section of the game remains uninterpreted at https://github.com/RoboPhred/oni-save-parser/blob/df9698a0233db210641b5dcdd523496566b46446/src/save-structure/parser.ts#L110

Could this segment potentially contain data related to the DLC, such as geysers on the other asteroids?

Upon further investigation using Duplicity, I noticed that only the gameObjects of my initial asteroid are visible. The coordinates are represented as X, Y, Z, but there is no apparent "planet" marker. Is there a marker that I may be overlooking?

I am curious about how ToolsNotIncluded.net manages to depict the entire cluster's layout from a single save game.

**Comment by RoboPhred** [comment]
simdata contains the map tiles, atmospheres, and pipe contents.  As far as I know, it doesnt contain any game objects of any sort.  In the code, that data is loaded wholesale into the native physics simulator dll and never directly touches any of the game object system.

I am not sure how game objects work on other asteroids, but I strongly suspect they are just offset in the world space.

I do know that they don't generate until you discover them, however.  Try landing on one of those asteroids and see if the game objects for those appear in the save data.

One consideration is that undiscovered geysers aren't 'real' geysers until they have been uncovered.  This was probably done for performance reasons.  It has been a long time since I was in this code and I don't remember the details exactly, but I believe there is some alternate game object serving as the marker data for a geyser that will spawn the actual geyser once uncovered by the map fog.

**Comment by StefanOltmann** [comment]
Thank you for your insights!

**Comment by StefanOltmann** [comment]
> I do know that they don't generate until you discover them, however. Try landing on one of those asteroids and see if the game objects for those appear in the save data.

I successfully incorporated them into the game objects by employing debug mode to access the asteroid, deploying a duplicate on it, exiting debug mode, and subsequently utilizing the sandbox tools to unveil everything.

While debug mode (activated with the backspace key) does display the entire map, it appears insufficient to effectively integrate items into the savegame. This phenomenon is intriguing. It seems that the sandbox tools' revealing function is more dependable.

Your observation regarding offsets is accurate. This implies that the bounds of all asteroids must be present in the savegame for the calculation of relative positions.

<img width="723" alt="screenshot" src="https://github.com/RoboPhred/oni-save-parser/assets/9299303/da67ba3c-4c56-41fe-9207-38efaeb79c84">

**Comment by StefanOltmann** [comment]
Upon closer examination, I discovered that all the necessary information is present in the initial savegame.

A game object named "SaveGame" hosts a behavior called "WorldGenSpawner", classified under the UserDefined type. Among the keys in this dictionary are "id", "location_x" and "location_y".

Sample output:
```
GeyserGeneric_hot_co2 at x=813 y=22
GeyserGeneric_hot_po2 at x=845 y=31
GeyserGeneric_chlorine_gas at x=925 y=143
GeyserGeneric_slush_water at x=33 y=52
GeyserGeneric_salt_water at x=53 y=57
GeyserGeneric_molten_niobium at x=837 y=131
GeyserGeneric_hot_steam at x=960 y=12
GeyserGeneric_steam at x=1004 y=12
```

The save game must be fresh, as revealing or generating the map will clear this data.

**Comment by StefanOltmann** [comment]
Damn, after working all day on this with four test files I created a fifth one and found this:
```
GeyserGeneric_steam, locationX=221, locationY=86
GeyserGeneric_chlorine_gas, locationX=76, locationY=199
GeyserGeneric_methane, locationX=113, locationY=253
GeyserGeneric, locationX=40, locationY=214
GeyserGeneric, locationX=94, locationY=256
GeyserGeneric, locationX=23, locationY=250
```

It appears to be quite random whether all Geyser types are determined or not.
All my files are the ones that get created automatically.

I was highly motivated to create my own ToolsNotIncluded.net in the past few days, but now I'm starting to feel some frustration. ONI seems to be a bit messed up in that regard.

**Comment by StefanOltmann** [comment]
I got some help from a modder on the Klei Forums and now everything is clear to me.

> but I believe there is some alternate game object serving as the marker data for a geyser that will spawn the actual geyser once uncovered by the map fog.

Yes, there is. And there is a special calculation logic to determine which geyser type it will become.

It's handled here:
https://github.com/StefanOltmann/oni-save-parser/blob/21fcd1964cd7ff165842b5ca46465872d85d3803/app/src/commonMain/kotlin/de/stefan_oltmann/oni/parser/SaveGameExtractor.kt#L244

I left you a thank you note in the README of my Kotlin port.
