### ISSUE TITLE
Please update sim-hashes to current SU content

### ISSUE THREAD

**Issue by ave-** [RoboPhred/oni-save-parser#6]
When you have time, can you please update sim-hashes to current SU content? We do not have supercoolant, isolator and other space materials from SU. Also, are these only consts from .Net assembly or may be they are stored in a save somehow?

**Comment by RoboPhred** [comment]
These values are only named in the assembly.  In the save file, they appear scattered about as hashes of the string.

The parser can infer the existence of new values by finding hashes it does not recognize, but nothing short of brute forcing the hash can determine what name it is.
The hash table contained by the parser is actually a developer convenience, the parser is able to load and save any new value even without the hash list being updated, as it just deals with numeric values.


I believe I updated the hashes for SU, but leaving this issue open until I can confirm.
