### ISSUE TITLE
Data doesn't survive roundtrip through JSON deserialization

### ISSUE THREAD

**Issue by Xaekai** [RoboPhred/oni-save-parser#8]
I made a quick `saver.js` in the root of a built `oni-save-parser` to test outputing the save in a JSON file to facilitate editing with a standard text editor.
```js

const savefile = `Hydrocarbon Eden`;
const savepath = '/home/xaekai/.config/unity3d/Klei/Oxygen Not Included/save_files/';


const fs = require('fs');

const {
    parseSaveGame,
    writeSaveGame,
    getBehavior,
    AIAttributeLevelsBehavior
} = require("./lib/index.js");

function loadJSON(filename){
    console.log('loading savedata from JSON', filename);
    // we could just use "require(`./${filename}.json`);" but this is more symmetrical
    const savedata = JSON.parse(fs.readFileSync(`${filename}.json`).toString());
    return savedata;
}

function loadFile(filename) {
    console.log('loading savefile', filename);
    const fileData = fs.readFileSync(`${filename}.sav`);
    return parseSaveGame(fileData.buffer);
}

function saveFile(filename, savedata) {
    console.log('writing savedata to', filename);
    // debug
    console.log('formatSave')
    const formatSave = writeSaveGame(savedata);
    console.log('serializing')
    const serialized = new Uint8Array(formatSave)
    fs.writeFileSync(`${filename}.sav`, serialized);
}

function saveJSON(filename, savedata) {
    console.log('writing savefile JSON', filename);
    fs.writeFileSync(`${filename}.json`, JSON.stringify(savedata, null, 2));
}


let savedata;
const loadsave = 1; // load the savefile
const savejson = 1; // save the savedata to JSON
const loadjson = 1; // load the savedata from JSON
const savesave = 1; // resave the savefile
const file = `${savepath}${savefile}`

if(loadsave){ savedata = loadFile(file); }
if(savejson){ saveJSON(file, savedata);  }
if(loadjson){ savedata = loadJSON(file); }
if(savesave){ saveFile(file, savedata);  }
```

But it doesn't survive the roundtrip. writeSaveGame chokes on the data when it's loaded from JSON.

I managed to do what I immediately wanted to through a node repl to edit the live object, but I thought I'd ask about this anyway, so maybe I can expand this into a full blown commandline save editor that can resave manually edited JSON files, among other things.

**Comment by RoboPhred** [comment]
The issue is some of the data remains unparsed and stored as Buffers, which are not handled by the Json serializer.  You can find these in game object behaviors with extraData and also in the world map data.

Saving to a text file might be problematic as the buffer contents of the world map takes up significant space, much more than the rest of the game objects.

You could work around this by only saving the game objects and base 64 encoding their small buffer fields, and require the original save to be provided when re-saving the Json.  The application could load the original, override the game objects with the Json file contents, then generate a new save file from the two.

**Comment by RoboPhred** [comment]
You will also need to handle Long values generated by the [long](https://www.npmjs.com/package/long) lib.  I'm not sure if these are used by the current save file, but the game does have the potential to generate them.  Just using .toString() on Long instances should be fine on serialize, but on parse you will need to load them in specially using the Long constructor.

**Comment by Xaekai** [comment]
Thanks for the information. Got busy with other stuff for a minute. I'll see about trying out merging the original save as a Buffer donor then overwrite with the JSON. Seems simple enough.
