### ISSUE TITLE
7.12 update needed

### ISSUE THREAD

**Issue by quonic** [RoboPhred/oni-save-parser#9]
[CURRENT_VERSION_MINOR](https://github.com/RoboPhred/oni-save-parser/blob/a0616808a3a87099aa41aeb82b5a33ceea723258/src/save-structure/parser.ts#L45) changing it to 12 seems okay as far as I can tell.

Maybe some option for the user to accept the risk of corrupting their save?

**Comment by RoboPhred** [comment]
Save version has been updated
